/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/loading/LoadingWindow.lh
 */
export class LoadingWindowRuntimeBase extends Laya.Box {
}

