/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/kwscz/kwsczRepairInfoWindow.lh
 */
export class kwsczRepairInfoWindowRunetimeBase extends Laya.Box {
    public closeBtn!: Laya.Button;
    public TextArea!: Laya.TextArea;
}

