/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/kwscz/kwsczRepairWindow.lh
 */
export class kwsczRepairWindowRuntimeBase extends Laya.Box {
    public closeBtn!: Laya.Button;
    public List!: Laya.List;
    public addBtn!: Laya.Button;
    public generateBtn!: Laya.Button;
    public resetBtn!: Laya.Button;
}

