/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/kwscz/kwsczRepairItem.lh
 */
export class kwsczRepairItemBase extends Laya.Box {
    public idInput!: Laya.TextInput;
    public levelInput!: Laya.TextInput;
    public skinInput!: Laya.TextInput;
    public versionInput!: Laya.TextInput;
    public delBtn!: Laya.Button;
    public albumInput!: Laya.TextInput;
    public coinInput!: Laya.TextInput;
}

