/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/main/MainMenuTabItem.lh
 */
export class MainMenuTabItemBase extends Laya.Box {
    public Button!: Laya.Button;
}

