/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/main/MainTabItem.lh
 */
export class MainTabItemBase extends Laya.Box {
    public Button!: Laya.Button;
}

