/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/main/MainWindow.lh
 */
export class MainWindowRuntimeBase extends Laya.Box {
    public List!: Laya.List;
}

