/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/main/MainMenuWindow.lh
 */
export class MainMenuWindowRuntimeBase extends Laya.Box {
    public titletxt!: Laya.Label;
    public List!: Laya.List;
    public closeBtn!: Laya.Button;
}

