/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/2d/tips/item/FractionItem.lh
 */
export class FractionItemBase extends Laya.Box {
    public content!: Laya.Sprite;
}

