/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/view/tips/item/TipsItem.lh
 */
export class TipsItemBase extends Laya.Box {
    public content!: Laya.Text;
}

